OrdersPortal.WebUI/Controllers/ComplaintsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using NLog;
using OrdersPortal.Application.Context;
using OrdersPortal.Application.Models.ViewModels;
using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Dto;
using OrdersPortal.Domain.Entities;
using OrdersPortal.Domain.Helpers;
using OrdersPortal.Domain.Repositories;


namespace OrdersPortal.WebUI.Controllers
{
	public class ComplaintsController : Controller
	{

		private readonly IOrderRepository _orderRepository;
		private readonly IComplaintsRepository _complaintsRepository;
		private readonly IOrderService _orderService;
		private readonly IComplaintsService _complaintsService;
		private readonly IMessageRepository _messageRepository;
		private readonly IAccountService _accountService;
		private readonly IMessageService _messageService;
		private readonly ApplicationContext _applicationContext;


		private readonly Logger _logger;
		private int[] _showStatusIds = { };
		private readonly int[] _showStatusUploads = { 1, 2 };
		private readonly int[] _showStatusNotConfirm = { 23 };
		private readonly int[] _showStatusNotPayed = { 22 };
		private readonly int[] _showStatusInWork = { 14, 16 };
		private readonly int[] _showStatusDecline = { 7, 17, 20, 21 };
		private readonly int[] _showStatusAll = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25 };

		private readonly int[] _showStatusInStock = { 9 };
		private readonly int[] _showStatusSolved = { 8 };
		private readonly int[] _showStatusInOrder = { 3 };
		private readonly int[] _showStatusInDelivery = { 25 };
		private readonly int[] _showStatusInProduction = { 6,16 };

		public ComplaintsController(IOrderRepository orderRepository, IOrderService orderService,
			IComplaintsRepository complaintsRepository, IComplaintsService complaintsService, IAccountService accountService,
			IMessageRepository messageRepository, IMessageService messageService, ApplicationContext applicationContext)
		{
			_orderRepository = orderRepository;
			_complaintsRepository = complaintsRepository;
			_orderService = orderService;
			_complaintsService = complaintsService;
			_messageRepository = messageRepository;

			_accountService = accountService;
			_messageService = messageService;
			_applicationContext = applicationContext;
			_logger = LogManager.GetCurrentClassLogger();
		}

		[Authorize]
		public ActionResult Index()
		{

			return RedirectToAction("List");
		}

		[Authorize]
		public ActionResult List()
		{

			return View();
		}
		public ActionResult ShowComplaintsList(int? page)
		{
			return RedirectToAction("List");
		}

		[HttpGet]
		public ActionResult ShowComplaintsListByStatus(string status, int? page)
		{

			return RedirectToAction("List");
		}


		public ActionResult AddComplaint()
		{
			var model = _complaintsService.PrepareUploadComplaintViewModel();

			return View(model);
		}



		[HttpPost]
		public ActionResult AddComplaint(UploadComplaintViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				_complaintsService.UploadComplaint(viewModel);
			}
			else
			{
				viewModel = _complaintsService.PrepareUploadComplaintViewModel();
				viewModel.ComplaintIssue = 0;

				return View(viewModel);
			}
			return RedirectToAction("List");
		}



		public ActionResult EditComplaint(int complaintid)
		{

			var model = _complaintsService.EditComplaint(complaintid);

			if (TempData["ViewData"] != null)
			{
				ViewData = (ViewDataDictionary)TempData["ViewData"];
				TempData["ViewData"] = null;
			}

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditComplaint(EditComplaintViewModel complaint)
		{

			if (ModelState.IsValid)
			{
				_complaintsService.SaveComplaint(complaint);

			}
			else
			{
				TempData["ViewData"] = ViewData;
				return RedirectToAction("EditComplaint", new { complaintid = complaint.ComplaintId });
			}
			return RedirectToAction("List");


		}
		public ActionResult ShowComplaintDetail(int complaintid)
		{

			var model = _complaintsService.GetComplaintDetailsByComplaintId(complaintid);
			return PartialView("~/Views/Complaints/Partials/PartialsShowComplaintDetails.cshtml", model);
		}
		public ActionResult ShowPhoto(int photoid)
		{
			var photo = _complaintsService.GetPhotoById(photoid);

			return PartialView("~/Views/Complaints/Partials/PartialsShowPhoto.cshtml", photo);
		}

		public ActionResult CheckOrder(string ordernum)
		{
			if (_complaintsService.CheckContrAgentOrder(ordernum))
			{
				ViewBag.Checked = "checkorderyes";
				ViewBag.CheckedText = "Замовлення знайдено";
			}
			else
			{
				ViewBag.Checked = "checkorderno";
				ViewBag.CheckedText = "Замовлення не знайдено";
			}
			return PartialView("~/Views/Complaints/Partials/CheckOrderBox.cshtml");
		}

		public ActionResult GetOrderSeries(string orderNumber)
		{
			List<ComplaintOrderSerieDto> orderSerie = _complaintsService.GetComplaintOrderSeriesByOrderNumber(orderNumber);

			return PartialView("~/Views/Complaints/Partials/OrderSeriesBox.cshtml", orderSerie);

		}
		public JsonResult GetSolutions(int id)
		{

			var result = _complaintsService.GetSolutionsByIssue(id);
			return Json(result, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public ActionResult ApproveSolution(int complaintId)
		{
			_complaintsService.ApproveComplaint(complaintId);

			return Redirect("ShowComplaintsList");
		}

		public ActionResult FillIssueSolutionList()
		{
			string result = "Список Проблем та Рішень завантажено успішно!";
			if (!_complaintsService.LoadIssueAndSolutionList())
			{
				result = "Сталася помилка!";
			}
			ViewBag.Text = result;
			return View();
		}

		[Authorize]
		public JsonResult TableDataGetComplaints(ComplaintTableDataModel tableDataModel, int? status)
		{
			try
			{

				OrderPortalUser currentUser = _accountService.GetById(_applicationContext.AccountId);
				var currentUserOrganizationList = currentUser.OrderPortalUserOrganizations.Select(o => o.Organization).ToList();


				IQueryable<Complaint> entitySet;

		//				private readonly int[] _showStatusInStock = { 9 };
		//private readonly int[] _showStatusSolved = { 8 };
		//private readonly int[] _showStatusInOrder = { 3 };
		//private readonly int[] _showStatusInProduction = { 6, 16 };
				switch (status)
				{
					case 1:
						_showStatusIds = _showStatusUploads;
						break;
					case 2:
						_showStatusIds = _showStatusInOrder;
						break;
					case 3:
						_showStatusIds = _showStatusInStock;
						break;
					case 4:
						_showStatusIds = _showStatusInProduction;
						break;
					case 5:
						_showStatusIds = _showStatusSolved;
						break;
					case 6:
						_showStatusIds = _showStatusDecline;
						break;
					default:
						_showStatusIds = _showStatusAll;
						break;
				}

				tableDataModel.Statuses = _showStatusIds;
				
				tableDataModel.Organizations = currentUserOrganizationList.Select(x => x.OrganizationId).ToArray();

				if (User.IsInRole("customer"))
				{
					tableDataModel.CustomerId = currentUser.Id;


				}
				else if (User.IsInRole("manager"))
				{

					tableDataModel.ManagerId = currentUser.Id;

				}
				else if (User.IsInRole("regionmanager"))
				{

					tableDataModel.RegionManagerId = currentUser.Id;

				}

				entitySet = _complaintsRepository.GetSortAndSearchList(tableDataModel);

				var count = entitySet.Count();
				var entity = entitySet.Skip(tableDataModel.Offset).Take(tableDataModel.Limit)
									  .Include(x => x.Status)
									  .Include(c => c.Customer)
									  .Include(b1 => b1.Customer.OrderPortalUserOrganizations)
									  .Include(b2 => b2.Customer.OrderPortalUserOrganizations.Select(t => t.Organization))
									  .Include(m => m.Manager)
									  .Include(m => m.ComplaintDecisions)
									  .Include(m => m.ComplaintDecisions.Select(v => v.ComplaintSolution))
									  .Include(n => n.ComplaintDecisions.Select(w => w.ComplaintIssue))
									  .ToList();

				IList<ComplaintListViewModel> tableData = ComplaintListViewModel.ConvertFromEntities(entity).ToList();


				var jsonTableData = new JsonDataTableModel<ComplaintListViewModel>
				{
					rows = tableData,
					total = count
				};

				return Json(jsonTableData, JsonRequestBehavior.AllowGet);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}
	}
}

OrdersPortal.WebUI/Views/Complaints/AddComplaint.cshtml
@model OrdersPortal.Application.Models.ViewModels.UploadComplaintViewModel
@{
	ViewBag.Title = "Завантажити рекламацію";

}
<input type="hidden" name="order" value="false">
<h2>@ViewBag.Title</h2>

<div class="row">
	<div class="col-12 col-md-9 col-lg-6 col-xl-4">
		@using (Html.BeginForm("AddComplaint", "Complaints", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
		{
			@Html.AntiForgeryToken()

			<hr />
			@Html.ValidationSummary()

			<div class="form-group">
				@Html.LabelFor(m => m.ComplaintOrderNumber, new { @class = "control-label" })
				<div class="col-12">
					@Html.TextBoxFor(m => m.ComplaintOrderNumber, new { @class = "form-control", @onchange = "javascript:CheckContrOrder()", id = "orderNum" })
					<div class="checkorderbox">

					</div>
				</div>
			</div>

			<div class="form-group pt-2">
				@Html.LabelFor(m => m.ComplaintOrderDeliverDate, new { @class = "control-label" })
				<div class="col-12">
					@Html.TextBoxFor(m => m.ComplaintOrderDeliverDate, new { @class = "form-control", id = "dp1" })

				</div>
			</div>

			<div class="form-group pt-2">
				@Html.LabelFor(m => m.ComplaintOrderDefineDate, new { @class = "control-label" })
				<div class="col-12">
					@Html.TextBoxFor(m => m.ComplaintOrderDefineDate, new { @class = "form-control", id = "dp2" })
				</div>
			</div>

			<div id="orderSeriesUpload"></div>

			@*<div class="form-group">
				 <div class="col-md-2 control-label"></div>
					<div class="col-md-10">
						<input type="checkbox" name="fancy-checkbox-primary" id="fancy-checkbox-primary" autocomplete="off" />
						<div class="btn-group">
							<label for="fancy-checkbox-primary" class="btn btn-standart">
								<span class="glyphicon glyphicon-ok"></span>
								<span> </span>
							</label>
							<label for="fancy-checkbox-primary" class="btn btn-default active">
								Primary Checkbox
							</label>
						</div>
					</div>
				</div>*@



			@Html.HiddenFor(m => m.CustomerName)


			<div class="form-group pt-2">
				@Html.LabelFor(m => m.ComplaintIssues, new { @class = "control-label" })
				<div class="col-12">
					<div>
						@Html.DropDownListFor(m => m.ComplaintIssue, Model.ComplaintIssues,
							new { @class = "form-select", id = "select-issue", onchange = "SolutionLoader();" })
						@Html.ValidationMessageFor(m => m.ComplaintIssue)
					</div>
				</div>
			</div>



			<div class="form-group pt-2">
				@Html.LabelFor(m => m.ComplaintSolutions, new { @class = "control-label" })
				<div class="col-12">
					<div>
						@Html.DropDownListFor(m => m.ComplaintSolution, Model.ComplaintSolutions,
							new { @class = "form-select col-12 col-md-4", id = "select-solution" })
						@Html.ValidationMessageFor(m => m.ComplaintSolution)
					</div>
				</div>
			</div>

			<div class="form-group pt-2">
				@Html.LabelFor(m => m.ComplaintDescription, new { @class = "control-label" })
				<div class="col-12">
					@Html.TextAreaFor(m => m.ComplaintDescription, new { @class = "form-control", @style = "height:200px;" })
				</div>
			</div>




			//-------------------------------------
			<div class="form-group pt-2">
				@Html.Label("Фото рекламації")
				<div class="col-12">
					<input type="file" id="File" name="File" class="multi-photo with-preview form-control" />
				</div>
			</div>

			//------------------------------------------------

			<div class="row justify-content-between pt-4">
				
				<div class="col-6">
					<input id="addButton" type="submit" class="btn btn-success" value="Додати" />
				</div>

				<div class="col-6">
					<input id="cancelButton" type="button" class="btn btn-secondary float-right" onclick="CancelButtonClick()" value="Відмінити" />
				</div>
				
			</div>
		}
	</div>
</div>

<script type="text/javascript">

	jQuery.validator.methods["date"] = function (value, element) { return true; }

</script>

<script src="/Scripts/extra/jquery.MultiFile.js" type="text/javascript" language="javascript"></script>


<script type="text/javascript">
	existOrderNumer = $('#orderNum').val();


	var attr = $('.validation-summary-errors').attr('data-valmsg-summary');

	if (existOrderNumer !== "")
	//	&& typeof attr !== typeof undefined && attr !== false)
	{
		CheckContrOrder();
		//LoadOrderSeries(existOrderNumer);
	}



	function LoadOrderSeries(orderNumber) {

		var url = "/Complaints/GetOrderSeries";
		//   OrderNum = document.getElementById('orderNum').value;
		$.ajax({
			url: url,
			contentType: "application/x-www-form-urlencoded; charset=windows-1251",
			type: "GET",
			data: {
				orderNumber: orderNumber
			},
			success: function (data) {
				$("#orderSeriesUpload").html(data);

			}
		});

	}
	function CheckContrOrder() {
		var url = "/Complaints/CheckOrder";
		OrderNum = document.getElementById('orderNum').value;
		$.ajax({
			url: url,
			contentType: "application/x-www-form-urlencoded; charset=windows-1251",
			type: "GET",
			data: {
				ordernum: OrderNum
			},
			success: function (data) {
				$(".checkorderbox").html(data);
				if ($("#checkOrder").hasClass("checkorderyes")) {
					$("#addButton").removeAttr("disabled");

					LoadOrderSeries(OrderNum);
				} else {

					$("#addButton").prop('disabled', true);

				}
			}
		});
	};

	function SolutionLoader() {

		var issue = $("#select-issue").val();
		var $dropdown = $("#select-solution");

		$dropdown.empty();

		if (issue != "") {
			$.ajax({
				url: "/Complaints/GetSolutions",
				contentType: "application/x-www-form-urlencoded; charset=windows-1251",
				type: "GET",
				data: {
					id: issue
				},
				success: function (data) {

					$.each(data, function () {
						$dropdown.append($("<option />").val(this.Value).text(this.Text));
					});
				}
			});
		}
	}

	function CancelButtonClick() {

		location.href = "/Complaints/List";
	}
</script>


<script type="text/javascript">
	// When the document is ready
	$(document).ready(function () {

		// RoleChecker();
		//  $("#enable-checkbox").bootstrapSwitch();
		$('#dp1').datepicker({
			format: "dd.mm.yyyy",
			autoclose: true
		}).on('changeDate', function (e) {
			$(this).datepicker('hide');
		});

		$('#dp2').datepicker({
			format: "dd.mm.yyyy",
			autoclose: true
		}).on('changeDate', function (e) {
			$(this).datepicker('hide');
		});


		$(function () {
			$('.multi-photo').MultiFile({
				accept: 'gif|jpg|jpeg|png',
				max: 10,
				STRING: {
					remove: 'X',
					selected: 'Обрано: $file',
					denied: 'Заборонено завантажувати даний тип фалів $ext!',
					duplicate: 'Дублікат:\n$file!'
				}
			});
		});
	});
</script>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

OrdersPortal.WebUI/Views/Complaints/EditComplaint.cshtml
@model OrdersPortal.Application.Models.ViewModels.EditComplaintViewModel
@{
    ViewBag.Title = "Редагувати рекламацію";
    var index = 0;
    //var Photos = Model.File;
    //List<ComplaintDetailPhotoViewModel> PhotosThubnail = new List<ComplaintDetailPhotoViewModel>();
    //foreach (var a in Photos)
    //{
    //  //  PhotosThubnail.Add(a.)
        
    //}
	}
<input type="hidden" name="order" value="false">
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("EditComplaint", "Complaints", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary()
    
    @Html.HiddenFor(m => m.ComplaintOrderNumber)
    @Html.HiddenFor(m => m.ComplaintId)
    @Html.HiddenFor(m => m.CustomerName)
    @Html.HiddenFor(m => m.ManagerName)

    <div class="form-group">
        @Html.LabelFor(m => m.ComplaintOrderNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Model.ComplaintOrderNumber
        </div>
    </div>

    foreach (var item in Model.ComplaintsOrderSeries)
    {
        <div class="form-group">
            <div class="col-md-2 control-label"></div>
            <div class="col-md-10">

                <input type="hidden" name="ComplaintsOrderSeries[@index].SerieName" id="@item.SerieName" autocomplete="off" value="@item.SerieName" />
                <input type="hidden" name="ComplaintsOrderSeries[@index].SerieGuid" id="@item.SerieGuid" autocomplete="off" value="@item.SerieGuid" />
                <input type="checkbox" data-val="true" value="true" name="ComplaintsOrderSeries[@index].Checked" id="ComplaintsOrderSeries[@index]" @(item.Checked ? "checked=checked  value=true": "" ) autocomplete="off"  />

                <div class="btn-group">
                    <label for="ComplaintsOrderSeries[@index]" class="btn btn-standart">
                        <span class="glyphicon glyphicon-ok"></span>
                        <span> </span>
                    </label>
                    <label for="ComplaintsOrderSeries[@index]" class="btn btn-default active">

                        @item.SerieName

                    </label>
                </div>
            </div>
        </div>

        index++;

    }

    <div class="form-group">
        @Html.LabelFor(m => m.ComplaintOrderDeliverDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
          @Model.ComplaintOrderDeliverDate.ToShortDateString()

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ComplaintOrderDefineDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Model.ComplaintOrderDefineDate.ToShortDateString()
        </div>
    </div>

    //-------------------------------------------------------------------
    <div class="form-group">
        <table class="table table-striped table-hover" data-toggle="table" id="decisiontable" onclick="OrderColours()">
            <thead>
            <tr>

                <th data-sortable="true" class="table-width40">№</th>
                <th data-sortable="true" class="table-width80">Дата</th>
                <th data-sortable="true" class="table-width150">Причина</th>
	            <th data-sortable="true" class="table-width150">Вирішення</th>
	            <th data-sortable="true" class="table-width150">Опис</th>

                <th data-sortable="true" class="normal-wrap table-width80">Узг. Дилером</th>
                <th data-sortable="true" class="normal-wrap table-width80">Узг. Менеджером</th>



            </tr>
            </thead>

            <tbody>

            @foreach (var b in Model.ComplaintDecisions)
            {
                <tr class='clickable-row' data-href='javascript:ShowComplaintDetail(@b.ComplaintId)'>
                    <td>@b.ComplaintId</td>
                    <td>@b.CreateDate</td>
                    <td>@b.ComplaintIssue.IssueText</td>
                    <td>@b.ComplaintSolution.SolutionText</td>
                    <td>@b.Description</td>
                    <td>
                        @if (b.CustomerApprove)
                        {<img src="/Images/sm_YES.png">}
                        else
                        {<img src="/Images/sm_NO.png">}
                    </td>
                    <td>
                        @if (b.ManagerApprove)
                        {<img src="/Images/sm_YES.png">}
                        else
                        {<img src="/Images/sm_NO.png">}
                    </td>
                </tr>
            }

            </tbody>

        </table>
    </div>
    //----------------------------------------------------------------------------

    @Html.HiddenFor(m => m.CustomerName, new { Value = ViewBag.CustName })

    

    <div class="form-group" id="choice-role">
        @Html.LabelFor(m => m.ComplaintIssues, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <div class="controls">
                @Html.DropDownListFor(m => m.ComplaintIssue, Model.ComplaintIssues,
                    new { @class = "form-control", style="min-width:600px;" ,id = "select-issue", onchange = "SolutionLoader();" })
	            @Html.ValidationMessageFor(m=>m.ComplaintIssue)
            </div>
        </div>
    </div>

	
    <div class="form-group" id="choice-role">
        @Html.LabelFor(m => m.ComplaintSolutions, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <div class="controls">
                @Html.DropDownListFor(m => m.ComplaintSolution, Model.ComplaintSolutions,
                    new { @class = "form-control", style = "min-width:600px;", id = "select-solution" })
	            @Html.ValidationMessageFor(m=>m.ComplaintSolution)
            </div>
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.ComplaintDescription, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.ComplaintDescription, new { @class = "form-control", @style = "max-width:600px; height:200px;" })
        </div>
    </div>

    

    //---------------
    
    <div class="col-md-12" style="padding-top:10px;">
                    <div style="font-size:12px; font-weight:300; padding:3px;"> Фото рекламації:</div>
                    @if (@Model.ComplaintPhotoThubmnails.Count > 0)
                    {
                        foreach (var b in @Model.ComplaintPhotoThubmnails)
                        {
                            if (b.ComplaintPhotoThumbnail != null)
                            {
                                <span style="padding:3px;">
                                    @Html.Raw("<img style='width:80px; height:60px;' onclick='javascript:ShowPhoto(" + b.ComplaintPhotoId + ")' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(b.ComplaintPhotoThumbnail) + "\" />")
                                </span>
                            }
                            else
                            {
                                <div>
                                    Немає фото
                                </div>
                            }
                        }
                    }
                    
                </div>
    
    //-------------------------------------
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="file" id="File" name="File" class="multi-photo with-preview" />
        </div>
    </div>

    //------------------------------------------------

    <div class="form-group">
        <div class="col-md-offset-2 col-md-3">
            <input id="addButton" type="submit"  class="btn btn-default" value="Змінити" />
        </div>

        <div class="col-md-offset-2 col-md-3">
            <input id="cancelButton" type="button" class="btn btn-default" onclick="CancelButtonClick()" value="Відмінити" />
        </div>
    </div>

}


<script type="text/javascript">

	jQuery.validator.methods["date"] = function (value, element) { return true; }


    function CancelButtonClick() {

        location.href = "/Complaints/ShowComplaintsList";
    }

</script>

<script src="/Scripts/extra/jquery.MultiFile.js" type="text/javascript" language="javascript"></script>


<script type="text/javascript">

	


    function CheckContrOrder() {
        var url = "/Complaints/CheckOrder";
        OrderNum = document.getElementById('orderNum').value;
        $.ajax({
            url: url,
            contentType: "application/x-www-form-urlencoded; charset=windows-1251",
            type: "GET",
            data: {
                ordernum: OrderNum
            },
            success: function (data) {
                $(".checkorderbox").html(data);
                if ($("#checkOrder").hasClass("checkorderyes")) {
                    $("#addButton").removeAttr("disabled");
                } else {

                    $("#addButton").prop('disabled', true);

                }
            }
        });
    };

    function SolutionLoader() {

        var issue = $("#select-issue").val();
        var $dropdown = $("#select-solution");

        $dropdown.empty();

        if (issue != "") {
            $.ajax({
                url: "/Complaints/GetSolutions",
                contentType: "application/x-www-form-urlencoded; charset=windows-1251",
                type: "GET",
                data: {
                    id: issue
                },
                success: function (data) {

                    $.each(data, function () {
                        $dropdown.append($("<option />").val(this.Value).text(this.Text));
                    });
                }
            });
        }
    }
</script>


<script type="text/javascript">
    // When the document is ready
    $(document).ready(function () {

        // RoleChecker();
        //  $("#enable-checkbox").bootstrapSwitch();
        $('#dp1').datepicker({
            format: "dd.mm.yyyy"
        });
        $('#dp2').datepicker({
            format: "dd.mm.yyyy"
        });


        $(function () {
            $('.multi-photo').MultiFile({
                accept: 'gif|jpg|jpeg|png',
                max: 10,
                STRING: {
                    remove: 'X',
                    selected: 'Обрано: $file',
                    denied: 'Заборонено завантажувати даний тип фалів $ext!',
                    duplicate: 'Дублікат:\n$file!'
                }
            });
		});

	    var issue = $("#select-issue").val();
	    if (issue != null && issue > 0) {
		    SolutionLoader();
	    }
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OrdersPortal.WebUI/Views/Complaints/FillIssueSolutionList.cshtml
@{
    string text = ViewBag.Text;
}
<div style="text-align: center">
    <h2>@text</h2>
</div>