OrdersPortal.WebUI/Controllers/OrganizationController.cs
using NLog;
using OrdersPortal.Application.Models.ViewModels;
using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Entities;
using OrdersPortal.Domain.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrdersPortal.WebUI.Controllers
{
    public class OrganizationController : Controller
    {
		private readonly IOrganizationRepository _organizationRepository;
		private readonly IOrganizationService _organizationService;
		private static readonly ILogger _logger = LogManager.GetCurrentClassLogger();


		public OrganizationController(IOrganizationRepository organizationRepository, IOrganizationService organizationService)
		{
			_organizationRepository = organizationRepository;
			_organizationService = organizationService;
		}
		// GET: Organization
		public ActionResult List()
		{
			var model = _organizationService.GetOrganizationList();
			return View(model);
		}


	

		public ActionResult Add()
		{
			OrganizationAddViewModel  viewModel = _organizationService.PrepareAddVierwModel(new OrganizationAddViewModel());
			return View(viewModel);
		}

	
		[HttpPost]
		[ValidateAntiForgeryToken]

		public ActionResult Add(OrganizationAddViewModel model)
		{
			if (ModelState.IsValid)
			{
				Organization organization = new Organization
				{
					OrganizationName = model.OrganizationName,
					Organization1cId = model.Organization1cId				

				};
				_organizationService.AddOrganization(organization);

			}

			return RedirectToAction("List");

		}

	
		public ActionResult Edit(int organizationId)
		{
			Organization organizatio = _organizationRepository.GetById(organizationId);
			return View(organizatio);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Organization organization)
		{
			_organizationService.EditOrganization(organization);

			return RedirectToAction("List");
		}

		public ActionResult Del(int organizationId)
		{
			try
			{
				_organizationService.RemoveOrganization(organizationId);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
			}

			return RedirectToAction("List");

		}
	}
}

OrdersPortal.WebUI/Controllers/RegionsController.cs
using System;
using System.Web.Mvc;
using NLog;
using OrdersPortal.Application.Models.ViewModels;
using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Entities;
using OrdersPortal.Domain.Repositories;


namespace OrdersPortal.WebUI.Controllers
{
    public class RegionsController : Controller
    {
	    private readonly IRegionRepository _regionRepository;
	    private readonly IRegionService _regionService;
	    private static readonly ILogger _logger = LogManager.GetCurrentClassLogger();


	    public RegionsController(IRegionRepository regionRepository, IRegionService regionService)
	    {
		    _regionRepository = regionRepository;
		    _regionService = regionService;
	    }
		//
		// GET: /Regions/

		public ActionResult Index()
		{
			return RedirectToAction("List");
		}

		// GET: /Regions/RegionList
		
		public ActionResult List()
		{
			var model = _regionService.GetRegionList();
			return View(model);
		}


		// GET: /Regions/RegionAdd

		public ActionResult Add()
		{
			return View();
		}

		// POST: /Regions/RegionAdd
		[HttpPost]
		[ValidateAntiForgeryToken]
	
		public ActionResult Add(RegionAddViewModel model)
		{
			if (ModelState.IsValid)
			{
				Region region = new Region
				{
					RegionName = model.RegionName

				};
				_regionService.AddRegion(region);
		
			}

			return RedirectToAction("List");

		}

		// GET: /Regions/RegionEdit		
		public ActionResult Edit(int regionId)
		{			
			Region region = _regionRepository.GetById(regionId);
			return View(region);
		}

		//
		// POST: /Regions/EditRegion
		[HttpPost]
		[ValidateAntiForgeryToken]		
		public ActionResult Edit(Region region)
		{
			_regionService.EditRegion(region);

			return RedirectToAction("List");
		}

		public ActionResult Del(int regionId)
		{
			try
			{
				_regionService.RemoveRegion(regionId);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
			}

			return RedirectToAction("List");

		}

	}
}

OrdersPortal.WebUI/Views/Organization/Add.cshtml
@model OrdersPortal.Application.Models.ViewModels.OrganizationAddViewModel
@{
	ViewBag.Title = "Додати організацію";
}

<h2>@ViewBag.Title</h2>

<div class="row">
	<div class="col-12 col-md-9 col-lg-6 col-xl-4">

		@using (Html.BeginForm("Add", "Organization", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
		{
			@Html.AntiForgeryToken()

			<hr />
			@Html.ValidationSummary()
			<div class="form-group">
				@Html.LabelFor(m => m.OrganizationName, new { @class = "col-2 control-label" })
				<div class="col-12">
					@Html.TextBoxFor(m => m.OrganizationName, new { @class = "form-control" })
				</div>
			</div>
			<div class="form-group">
				@Html.LabelFor(m => m.Organization1cId, new { @class = "col-8 control-label" })
				<div class="col-12">
					@Html.DropDownListFor(m => m.Organization1cId, Model.Organization1cList.Select(x => new SelectListItem
					{
						Text = x.Name,
						Value = x.Code.ToString()
					}), new { @class = "form-select", @id = "select-managerguid" })
				</div>
			</div>
			<div class="row justify-content-between pt-4">

				<div class="col-6">
					<input id="addButton" type="submit" class="btn btn-success" value="Додати" />
				</div>

				<div class="col-6">
					<input id="cancelButton" type="button" class="btn btn-secondary float-right" onclick="CancelButtonClick()" value="Відмінити" />
				</div>

			</div>

		}
	</div>
</div>
<script>
	function CancelButtonClick() {

		location.href = "/Organization/List";
	}
</script>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

OrdersPortal.WebUI/Views/Organization/Edit.cshtml
@model OrdersPortal.Domain.Entities.Organization
@{
	ViewBag.Title = "Редагування Організації";
}

<h2>@ViewBag.Title.</h2>
@using (Html.BeginForm("Edit", "Organization", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
	@Html.AntiForgeryToken()

	<hr />
	@Html.ValidationSummary()
	<div class="form-group">
		@Html.LabelFor(m => m.OrganizationName, new { @class = "col-2 control-label" })
		<div class="col-12">
			@Html.TextBoxFor(m => m.OrganizationName, new { @class = "form-control" })
		</div>
	</div>
	<div class="form-group col-12 pt-4">
		<div class="col-3 d-inline-block">
			<input id="addButton" type="submit" class="btn btn-success" value="Зберегти" />
		</div>

		<div class="col-3 d-inline-block">
			<input id="cancelButton" type="button" class="btn btn-secondary" onclick="CancelButtonClick()" value="Відмінити" />
		</div>
	</div>

}
<script>
	function CancelButtonClick() {

		location.href = "/Organization/List";
	}
</script>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

OrdersPortal.WebUI/Views/Organization/List.cshtml
@model List<OrdersPortal.Domain.Entities.Organization>
@{
	ViewBag.Title = "Організації";

}

<div>
	<h2>@ViewBag.Title</h2>
</div>


@Html.AntiForgeryToken()
<div>
	@Html.ActionLink("Додати організацію", "Add", null, new { @class = "btn btn-success" })
</div>
<table class="table table-striped table-hover " data-toggle="table" data-search="true">
	<thead>
		<tr>
			<th>#</th>
			<th>Назва організації</th>
			<th>Код організації в 1С</th>
			<th>Дії</th>
		</tr>
	</thead>

	<tbody>
		@foreach (var b in Model)
		{
		<tr>
			<td>@b.OrganizationId</td>
			<td>@b.OrganizationName</td>
			<td>@b.Organization1cId</td>
			<td>
				<p>
					@Html.ActionLink("Edit", "Edit", "Regions", new { regionId = b.OrganizationId }, new { title = "Управління" })
					@Html.ActionLink("Del", "Del", "Regions", new { regionId = b.OrganizationId, message = "" }, new { title = "Управління" })
				</p>
			</td>
		</tr>
		}
	</tbody>
</table>