OrdersPortal.WebUI/Controllers/AnalyticsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NLog;
using OrdersPortal.Application.Context;
using OrdersPortal.Application.Models;
using OrdersPortal.Application.Models.ViewModels;
using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Entities;
using OrdersPortal.Domain.Models;
using OrdersPortal.Domain.Models.Analytics;
using OrdersPortal.Domain.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrdersPortal.WebUI.Controllers
{
    public class AnalyticsController : Controller
    {

		private readonly IAccountRepository _accountRepository;
		private readonly IAccountService _accountService;
		private readonly IAnalyticsService _analyticsService;
		private readonly ApplicationContext _applicationContext;
		private Logger _logger;
		public UserManager<OrderPortalUser> UserManager { get; private set; }

		public AnalyticsController(IAccountRepository accountRepository, IAccountService accountService, IAnalyticsService analyticsService,
			ApplicationContext applicationContext)
		{
			_accountRepository = accountRepository;
			_accountService = accountService;
			_analyticsService = analyticsService;
			_applicationContext = applicationContext;
			_logger = LogManager.GetCurrentClassLogger();
			var dbContextProvider = DependencyResolver.Current.GetService<IDbContextProvider>();
			UserManager = new UserManager<OrderPortalUser>(new UserStore<OrderPortalUser>(dbContextProvider.DbContext));

		}
		// GET: Finance
		[Authorize]
		public ActionResult Index()
		{

			return RedirectToAction("OrderAnalytics");
		}
		[Authorize]
		public ActionResult OrderAnalytics()
		{

			var viewModel = _analyticsService.PrepareAnalyticsOrdersListViewModel(null);

			return View(viewModel);
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult OrderAnalytics(OrderAnalyticsListViewModel viewModel)
		{
			try
			{

				viewModel = _analyticsService.PrepareAnalyticsOrdersListViewModel(viewModel);

				viewModel.AnalyticsCategoryOrderList = _analyticsService.GetOrderAnalyticsList(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);

				viewModel.ModelCharts = _analyticsService.GetOrderAnalyticsChartsData(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);

				viewModel.AnalyticsProfileSystemChartList = _analyticsService.GetProfileSystemAnalytics(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);

				if (viewModel.AnalyticsCategoryOrderList != null && viewModel.AnalyticsCategoryOrderList.Count > 0)
				{
					viewModel.AvarageBill = Math.Round(viewModel.AnalyticsCategoryOrderList.Sum(x => x.AnalyticsOrderList.Sum(y => y.TotalValue)) / viewModel.AnalyticsCategoryOrderList.Sum(x => x.AnalyticsOrderList.Count), 2);
				}
				return View(viewModel);
			}
			 catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}


	}
}

OrdersPortal.WebUI/Controllers/FinanceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NLog;

using OrdersPortal.Application.Models;
using OrdersPortal.Application.Models.ViewModels;
using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Dto.Customer1cOrder;
using OrdersPortal.Domain.Models;

namespace OrdersPortal.WebUI.Controllers
{
	public class FinanceController : Controller
	{

		private readonly IFinanceService _financeService;
		private static readonly ILogger _logger = LogManager.GetCurrentClassLogger();
		private const int _topWdsRatingNumber = 10;
		private const int _daysInWdsRating = 1;


		public FinanceController(IFinanceService financeService)
		{

			_financeService = financeService;
		}


		// GET: Finance
		[Authorize]
		public ActionResult Index()
		{

			return RedirectToAction("List");
		}

		[Authorize]
		public ActionResult List()
		{
			var viewModel = _financeService.PrepareFinanceOrdersListViewModel();
			return View(viewModel);
		}


		[Authorize]
		public JsonResult TableDataGetFinanceOrders(FinanceTableDataModel financeTableDataModel)
		{
			try
			{
				IList<FinanceOrder> tableData = _financeService.GetFinanceOrderList(financeTableDataModel);

				JsonFinanceDataTableModel jsonTableData = new JsonFinanceDataTableModel
				{
					rows = tableData.ToList().GetRange(financeTableDataModel.Offset, Math.Min(financeTableDataModel.Limit, tableData.Count - financeTableDataModel.Offset)),
					total = tableData.Count,
					SumTotalValue = tableData.Sum(x => x.TotalValue),
					SumAdvanceValue = tableData.Sum(x => x.AdvanceValue),
					SumBalanceValue = tableData.Sum(x => x.BalanceValue),
					SumQuantityConstructions = tableData.Sum(x => x.QuantityConstructions)
				};

				return Json(jsonTableData, JsonRequestBehavior.AllowGet);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}


		[Authorize]
		public ActionResult CashFlow()
		{

			var viewModel = _financeService.PrepareFinanceCashFlowViewModel(null);

			return View(viewModel);
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CashFlow(FinanceCashFlowViewModel viewModel)
		{
			try
			{

				viewModel = _financeService.PrepareFinanceCashFlowViewModel(viewModel);
				viewModel.FinanceDayCashFlowList = _financeService.GetFinanceDayCashFlowList(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);

				return View(viewModel);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}

		[Authorize]
		public ActionResult CashFlowExportCsv(FinanceCashFlowViewModel viewModel)
		{
			try
			{
				viewModel = _financeService.PrepareFinanceCashFlowViewModel(viewModel);

				List<FinanceDayCashFlow> financeDayCashFlowList = _financeService.GetFinanceDayCashFlowList(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);
				FileContentResult file = _financeService.CashFlowGenerateFile(financeDayCashFlowList);

				return file;
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}

		[Authorize]
		public ActionResult Reconciliation()
		{
			var viewModel = _financeService.PrepareFinanceReconciliationViewModel(null);

			return View(viewModel);
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Reconciliation(FinanceReconciliationViewModel viewModel)
		{
			try
			{
				viewModel = _financeService.PrepareFinanceReconciliationViewModel(viewModel);

				viewModel.FinanceReconciliationList = _financeService.GetFinanceReconciliationList(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);
				return View(viewModel);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}
		[Authorize]
		public ActionResult ReconciliationExportCsv(FinanceReconciliationViewModel viewModel)
		{
			try
			{
				viewModel = _financeService.PrepareFinanceReconciliationViewModel(viewModel);

				var financeReconciliationList = _financeService.GetFinanceReconciliationList(viewModel.ContrAgentCode, viewModel.StartDate, viewModel.EndDate);
				FileContentResult file = _financeService.ReconciliationGenerateFile(financeReconciliationList);

				return file;
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				return null;
			}
		}

		[Authorize]
		public ActionResult OrdersPayments()
		{

			OrdersPaymentsViewModel viewModel = _financeService.PrepareOrdersPaymentsViewModel();

			return View(viewModel);
		}

		[Authorize]
		[HttpGet]
		public ActionResult GetWdsActionCodes()
		{
			WdsActionCodeViewModel model = _financeService.PrepareWdsActionViewModel();

			return View(model);
		}

		[Authorize]
		[HttpPost]
		public ActionResult GetWdsActionCodes(WdsActionCodeViewModel model)
		{
			model = _financeService.GetWdsCodes(model);

			return View(model);
		}
		[Authorize]
		public ActionResult GetOrdersPayments(OrdersPaymentsViewModel viewModel)
		{

			//var viewModel = new OrdersPaymentsViewModel();
			try
			{
				viewModel = _financeService.GetGetOrderPayments(viewModel);
			}
			catch (Exception ex)
			{
				_logger.Error(ex);
			}
			return PartialView("~/Views/Finance/GetOrdersPayments.cshtml", viewModel);

		}
		[Authorize]
		public ActionResult GetWdsActionRating()
		{
			List<WdsActionRatingListViewModel> viewModel = _financeService.GetWdsActionRating(_topWdsRatingNumber, _daysInWdsRating);

			return View(viewModel);
		}

		[Authorize]
		[HttpPost]
		public ActionResult SetOrdersPayments(OrdersPaymentsViewModel model)
		{
			try
			{

				if ((ModelState.IsValid && model.AvailableAdvance >= model.Payments.Sum(x => x.Payment)))
				{
					if (!_financeService.ProceedOrdersPayments(model))
					{
						_logger.Error($"Payment customer: {model.ContrAgentCode} was delayed as exist payment is progress");
						ViewBag.Error = "Delay";
						return View();
					}
				}
				else
				{
					_logger.Error($"Payment customer: {model.ContrAgentCode} has errors");
					ViewBag.Error = "Error";
					return View();
				}

			}
			catch (Exception ex)
			{
				_logger.Error(ex);
				ViewBag.Error = "Error";
				return View();
			}
			return View();
		}

		[Authorize]
		public ActionResult GetCustomerBillList()
		{

			var viewModel = _financeService.GetCustomerBillList(null);
			return View(viewModel);
		}

		[Authorize]
		[HttpPost]
		public ActionResult GetCustomerBillList(CustomerBillListViewModel viewModel)
		{
			viewModel = _financeService.GetCustomerBillList(viewModel);
			return View(viewModel);
		}

		[Authorize]
		public ActionResult CreateCustomerBill()
		{

			var viewModel = _financeService.GetCustomerBillValues();
			return View(viewModel);
		}

		[Authorize]
		public ActionResult DownloadCustomerBillByGuid(string guid)
		{
			var file = _financeService.GetCustomerBillByGuid(guid);

			byte[] data = Convert.FromBase64String(file);



			return File(data, "application/pdf");



			//string url = "<object style='width:80px; height:60px;' > <a target=\"blank\" alt=\"Відкрити в новому вікні\" href=\"data:application/pdf;base64,"
			//             + viewModel + "\">order.pdf</a> </object>";
			//return Json(url, JsonRequestBehavior.AllowGet);

		}

		[Authorize]
		[HttpPost]
		public ActionResult CreateCustomerBill(Create1COrderViewModel model)
		{

			_financeService.CreateCustomerBill(model);
			return RedirectToAction("GetCustomerBillList");
		}

	}
}

OrdersPortal.WebUI/Controllers/StatsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

using NLog;

using OrdersPortal.Application.Models.ViewModels;
using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Entities;
using OrdersPortal.Domain.Repositories;
using OrdersPortal.Infrastructure.EntityFramework;

namespace OrdersPortal.WebUI.Controllers
{
	public class StatsController : Controller
	{

	
		private readonly IStatService _statService;
		private Logger _logger;
		//public UserManager<OrderPortalUser> UserManager { get; private set; }

		public StatsController(IStatService statService)
		{

			_statService = statService;
			_logger = LogManager.GetCurrentClassLogger();
			//var dbContextProvider = DependencyResolver.Current.GetService<IDbContextProvider>();
			//UserManager = new UserManager<OrderPortalUser>(new UserStore<OrderPortalUser>(dbContextProvider.DbContext));

		}
		

		public ActionResult HelpServiceStat(string startDateHs, string endDateHs)
		{


			HelpServiceStatsViewModel model = _statService.GetHelpServiceStats(startDateHs, endDateHs);
			return View(model);
		}

	}
}

OrdersPortal.WebUI/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using NLog;

using OrdersPortal.Application.Services;
using OrdersPortal.Domain.Entities;
using OrdersPortal.Domain.Repositories;

namespace OrdersPortal.WebUI.Controllers
{
    public class VideoController : Controller
    {

	    private readonly IVideoContentService _videoContentService;
	    private readonly IVideoContentRepository _videoContentRepository;
	    private Logger _logger;

	    public VideoController(IVideoContentService videoContentService, IVideoContentRepository videoContentRepository)
	    {

		    _videoContentService = videoContentService;
		    _videoContentRepository = videoContentRepository;
		    _logger = LogManager.GetCurrentClassLogger();
		    

	    }


		// GET: Video
		public ActionResult Index()
        {
	        return RedirectToAction("List");
        }
        public ActionResult List()
        {
	        var list = _videoContentService.GetList();
	        return View(list);
        }

        public ActionResult Add()
        {
	        return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Add(VideoContent model)
        {
	        if (ModelState.IsValid)
	        {
		        try
		        {
			        _videoContentService.Add(model);
		        }
		        catch (Exception ex)
		        {
					_logger.Error(ex);
		        }
		        
		        return RedirectToAction("List");
			}

	        return View(model);

        }

        public ActionResult Edit(int id)
        {
	        VideoContent videoContent = _videoContentRepository.GetById(id);
	        return View(videoContent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VideoContent videoContent)
        {
	        try
	        {
		        _videoContentService.Edit(videoContent);
	        }
	        catch (Exception ex)
	        {
		        _logger.Error(ex);
			}

	        return RedirectToAction("List");
        }

        public ActionResult Remove(int id)
        {
	        try
	        {
		        _videoContentService.Remove(id);
	        }
	        catch (Exception ex)
	        {
		        _logger.Error(ex);
	        }

	        return RedirectToAction("List");

        }
	}
}

OrdersPortal.WebUI/Views/Shared/_FinanceMenu.cshtml
<li class="nav-item dropdown  col-6 col-md-auto">
	<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
		<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-money-check-alt fa-lg icon-green"></i></div>
		Фінанси
	</a>
	<div class="dropdown-menu">
		@Html.ActionLink("Взаєморозрахунки", "Reconciliation", "Finance", null, new { @class = "dropdown-item" })
		@Html.ActionLink("Рух коштів", "CashFlow", "Finance", null, new { @class = "dropdown-item" })
		<div class="dropdown-divider"></div>
		@Html.ActionLink("Аналітика", "OrderAnalytics", "Analytics", null, new { @class = "dropdown-item" })
		<div class="dropdown-divider"></div>
		@Html.ActionLink("Оплата", "OrdersPayments", "Finance", null, new { @class = "dropdown-item" })
		<div class="dropdown-divider"></div>
		@Html.ActionLink("Акція WDS", "GetWdsActionCodes", "Finance", null, new { @class = "dropdown-item" })
		@*@Html.ActionLink("Бонус дня", "GetWdsActionRating", "Finance", null, new { @class = "dropdown-item" })*@
		<div class="dropdown-divider"></div>
		@Html.ActionLink("Рахунки", "GetCustomerBillList", "Finance", null, new { @class = "dropdown-item" })
	</div>
</li>

OrdersPortal.WebUI/Views/Shared/_Layout.cshtml
@using OrdersPortal.Domain.Entities
<!DOCTYPE html>
<html lang="uk">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title</title>

	@*<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>*@
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
	@*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>*@


	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Marmelad&subset=cyrillic">


	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
	<script>
		(function (i, s, o, g, r, a, m) {
			i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
				(i[r].q = i[r].q || []).push(arguments)
			}, i[r].l = 1 * new Date(); a = s.createElement(o),
				m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
		})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

		ga('create', 'UA-99576319-1', 'auto');
		ga('send', 'pageview');
	</script>


</head>
<body class="d-flex flex-column min-vh-100">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="flex-wrap: wrap">
		<div id="nav-container1" class="container-fluid col-xxl-10 col-12">
			<a href="/"><img src="/Images/vikna_logo_white2.png" height="54px" class="p-1"></img></a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse justify-content-between" id="navbarColor01">
				<div class="navbar-nav col-6 col-md-9 justify-content-start">
					@if (Request.IsAuthenticated)
					{
						@*<li class="nav-item col-6 col-md-auto text-white bg-wdsrating-action bg-wdsrating-action:hover">
								<a class="nav-link" href="/Finance/GetWdsActionRating" id="WdsRatingActionMenu">
									<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-list-ol fa-lg"></i></div>
									Бонус дня
									<span class="sr-only"></span>
								</a>
							</li>*@
						<li class="nav-item col-6 col-md-auto text-white bg-wds-action bg-wds-action:hover">
							<a class="nav-link" href="/Finance/GetWdsActionCodes" id="WdsActionMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-gift fa-lg"></i></div>
								Акція WDS
								<span class="sr-only"></span>
							</a>
						</li>

						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="/Orders/List" id="OrdersListMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-shopping-basket fa-lg text-success"></i></div>
								Замовлення
								<span class="sr-only"></span>
							</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="/Complaints/List" id="ComplaintsListMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-tools fa-lg text-warning"></i></div>
								Рекламації
								<span class="sr-only"></span>
							</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="/OrderParts/List" id="OrderPartsListMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-cart-plus fa-lg text-success"></i></div>
								Дозамовлення
								<span class="sr-only"></span>
							</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="/Finance/List" id="StatusOrdersListMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-clipboard-list fa-lg icon-yellow"></i></div>

								Статус
								<span class="sr-only"></span>
							</a>
						</li>

						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="/Files/List" id="FilesListMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-cloud-download-alt fa-lg icon-cyan"></i></div>
								Файли
								<span class="sr-only"></span>
							</a>
						</li>
						<li class="nav-item col-6 col-md-auto">
							<a class="nav-link" href="/Video/List" id="VideoListMenu">
								<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fab fa-youtube fa-lg icon-purple"></i></div>
								Відео
								<span class="sr-only"></span>
							</a>
						</li>

						if (User.IsInRole("customer") || User.IsInRole("regionmanager"))
						{
							<li class="nav-item dropdown  col-3 col-md-auto">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" style="color: pink" aria-expanded="false">
									<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-phone-square-alt fa-lg icon-pink"></i></div>
									Виклик
								</a>
								<div class="dropdown-menu">
									<div class="dropdown-divider"></div>
									@Html.ActionLink("Керівник відділу продажів", "CallManager", "HelpService", routeValues: new { @helpServiceType = HelpServiceTypesEnum.Sales }, htmlAttributes: new { @class = "dropdown-item", id = "CallSalesManagerLink" })
									<div class="dropdown-divider"></div>
									@Html.ActionLink("Керівник сервісного відділу", "CallManager", "HelpService", routeValues: new { @helpServiceType = HelpServiceTypesEnum.Service }, htmlAttributes: new { @class = "dropdown-item", id = "CallServiceManagerLink" })
									<div class="dropdown-divider"></div>
									@Html.ActionLink("Керівник відділу логістики", "CallManager", "HelpService", routeValues: new { @helpServiceType = HelpServiceTypesEnum.Logistic }, htmlAttributes: new { @class = "dropdown-item", id = "CallLogisticManagerLink" })
								</div>
							</li>
						}
						if (User.IsInRole("director") || User.IsInRole("admin"))
						{
							<li class="nav-item dropdown  col-3 col-md-auto">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
									<div class="d-none d-sm-inline d-md-inline  d-lg-none d-xl-inline"><i class="fas fa-chart-bar fa-lg icon-red"></i></div>
									Статистика
								</a>
								<div class="dropdown-menu">
									@Html.ActionLink("S.O.S.", "HelpServiceStat", "Stats", null, new { @class = "dropdown-item", id = "HelpServiceStatLink" })
									@Html.ActionLink("Відео", "List", "Video", null, new { @class = "dropdown-item", id = "VideoContentLink" })
								</div>
							</li>
						}
						Html.RenderAction("ShowFinanceMenu", "Account");


					}
				</div>
				<div class="navbar-nav col-6 col-md-3 justify-content-end">
					@Html.Partial("_LoginPartial")
				</div>

			</div>
		</div>
	</nav>


	<div class="container-fluid body-content col-12 col-xxl-9 col-xl-10 pt-3">
		@RenderBody()

	</div>

	<footer class="mt-auto">
		@*<div>
				@if (Request.IsAuthenticated)
				{
					Html.RenderAction("ShowUserManagers", "Account");
				}
			</div>*@

		<hr />
		<div class="text-center">
			<p>&copy; 2015-@DateTime.Now.Year Вікна Стиль</p>
		</div>
	</footer>

	<script>

		var $element = $("#nav-container1")[0];

		var lastHeight = $("#nav-container1")[0].offsetHeight;

		function checkForChanges() {
			if ($("#nav-container1")[0].offsetHeight > 60) {
				$("#nav-container1").removeClass("col-xxl-10");
			}
		}

		window.addEventListener("DOMContentLoaded", e => {
			checkForChanges();
		});

		window.addEventListener("resize", e => {
			checkForChanges();
		});
	</script>
</body>
</html>

OrdersPortal.WebUI/Views/Shared/_UserManagers.cshtml
@model OrdersPortal.Application.Models.ViewModels.UserManagersViewModel
<div class="container col-12">
	<div class="row col-12 justify-content-center text-center text-uppercase text-white pt-2 pb-2 fs-4">
		Ваші персональні менеджери, які завжди допоможуть вам, з питань персонального корпоративного обслуговування клієнтів
	</div>
	<div class="row col-12 d-flex justify-content-between">
		<div class="regional-manager col-12 col-md-auto">
			<div class="rm-photo d-none d-sm-inline "><img height="180px" width="180px" src="@Model.RegionManagerImagePath"></div>
			<div class="rm-contact-info">
				<div class="rm-info-name">@Model.RegionManagerName</div>
				<div class="rm-info-role">@Model.RegionManagerRole</div>
				<div class="rm-info-email"><i class="far fa-lg fa-envelope"></i> @Model.RegionManagerEmail</div>
				<div class="rm-info-tel"><i class="fas fa-lg fa-flip-horizontal fa-phone"></i> @Model.RegionManagerPhone </div>
			</div>
		</div>
		<div class="sales-manager col-12 col-md-auto">
			<div class="sm-photo  d-none d-sm-inline"><img height="180px" width="180px" src="@Model.SalesManagerImagePath"></div>
			<div class="sm-contact-info">
				<div class="sm-info-name">@Model.SalesManagerName</div>
				<div class="sm-info-role">@Model.SalesManagerRole </div>
				<div class="sm-info-email"><i class="far fa-lg fa-envelope"></i> @Model.SalesManagerEmail</div>
				<div class="sm-info-tel"><i class="fas fa-lg fa-flip-horizontal fa-phone"></i> @Model.SalesManagerPhone</div>
			</div>
		</div>
	</div>
</div>